// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package authpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AuthorityApiClient is the client API for AuthorityApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuthorityApiClient interface {
	VerifyToken(ctx context.Context, in *AuthorizeTokenRequest, opts ...grpc.CallOption) (*AuthorizeTokenResponse, error)
}

type authorityApiClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthorityApiClient(cc grpc.ClientConnInterface) AuthorityApiClient {
	return &authorityApiClient{cc}
}

func (c *authorityApiClient) VerifyToken(ctx context.Context, in *AuthorizeTokenRequest, opts ...grpc.CallOption) (*AuthorizeTokenResponse, error) {
	out := new(AuthorizeTokenResponse)
	err := c.cc.Invoke(ctx, "/authority.AuthorityApi/VerifyToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthorityApiServer is the server API for AuthorityApi service.
// All implementations must embed UnimplementedAuthorityApiServer
// for forward compatibility
type AuthorityApiServer interface {
	VerifyToken(context.Context, *AuthorizeTokenRequest) (*AuthorizeTokenResponse, error)
	mustEmbedUnimplementedAuthorityApiServer()
}

// UnimplementedAuthorityApiServer must be embedded to have forward compatible implementations.
type UnimplementedAuthorityApiServer struct {
}

func (UnimplementedAuthorityApiServer) VerifyToken(context.Context, *AuthorizeTokenRequest) (*AuthorizeTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyToken not implemented")
}
func (UnimplementedAuthorityApiServer) mustEmbedUnimplementedAuthorityApiServer() {}

// UnsafeAuthorityApiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthorityApiServer will
// result in compilation errors.
type UnsafeAuthorityApiServer interface {
	mustEmbedUnimplementedAuthorityApiServer()
}

func RegisterAuthorityApiServer(s grpc.ServiceRegistrar, srv AuthorityApiServer) {
	s.RegisterService(&AuthorityApi_ServiceDesc, srv)
}

func _AuthorityApi_VerifyToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthorizeTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthorityApiServer).VerifyToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/authority.AuthorityApi/VerifyToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthorityApiServer).VerifyToken(ctx, req.(*AuthorizeTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AuthorityApi_ServiceDesc is the grpc.ServiceDesc for AuthorityApi service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthorityApi_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "authority.AuthorityApi",
	HandlerType: (*AuthorityApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "VerifyToken",
			Handler:    _AuthorityApi_VerifyToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/authority.proto",
}
