// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package crmpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CrmApiClient is the client API for CrmApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CrmApiClient interface {
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error)
}

type crmApiClient struct {
	cc grpc.ClientConnInterface
}

func NewCrmApiClient(cc grpc.ClientConnInterface) CrmApiClient {
	return &crmApiClient{cc}
}

func (c *crmApiClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error) {
	out := new(CreateResponse)
	err := c.cc.Invoke(ctx, "/crm.CrmApi/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CrmApiServer is the server API for CrmApi service.
// All implementations must embed UnimplementedCrmApiServer
// for forward compatibility
type CrmApiServer interface {
	Create(context.Context, *CreateRequest) (*CreateResponse, error)
	mustEmbedUnimplementedCrmApiServer()
}

// UnimplementedCrmApiServer must be embedded to have forward compatible implementations.
type UnimplementedCrmApiServer struct {
}

func (UnimplementedCrmApiServer) Create(context.Context, *CreateRequest) (*CreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedCrmApiServer) mustEmbedUnimplementedCrmApiServer() {}

// UnsafeCrmApiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CrmApiServer will
// result in compilation errors.
type UnsafeCrmApiServer interface {
	mustEmbedUnimplementedCrmApiServer()
}

func RegisterCrmApiServer(s grpc.ServiceRegistrar, srv CrmApiServer) {
	s.RegisterService(&CrmApi_ServiceDesc, srv)
}

func _CrmApi_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrmApiServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/crm.CrmApi/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrmApiServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CrmApi_ServiceDesc is the grpc.ServiceDesc for CrmApi service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CrmApi_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "crm.CrmApi",
	HandlerType: (*CrmApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _CrmApi_Create_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/crm.proto",
}
